// Catálogo de cultivares — Coasul
// PMS/PMG ainda não preenchido (null) — completar depois com dados oficiais
// Extraído de: histórico de vendas de milho (imagem) e SEMENTE_DE_SOJA_VENDIDAS.pdf
//
// Usado pela busca/sugestão do campo "Cultivar cotada" (ver o bloco de busca
// de cultivar em app.js). Cada item: { nome, pms }. pms em gramas por 1.000
// sementes — null enquanto não temos o valor oficial; o indicador de PMS/PMG
// automático só aparece pra itens com esse dado preenchido.
const CULTIVARES = {
  soja: [
    { nome: "51IX51RSF (TROVAO) I2X", pms: null },
    { nome: "53IX55RSF (IMUNE) TF I2X", pms: null },
    { nome: "55I57RSF IPRO (ZEUS)", pms: null },
    { nome: "55IX56RSF I2X (ORION)", pms: null },
    { nome: "56IX58RSF I2X (TITANIUM)", pms: null },
    { nome: "57I59RSF IPRO (CROMO)", pms: null },
    { nome: "57K56RSF TF CE (GRAFENO)", pms: null },
    { nome: "AS-3577 XTEND", pms: null },
    { nome: "AS-3595 (5995 I2X)", pms: null },
    { nome: "DM 54IX57RSF I2X", pms: null },
    { nome: "DM 56I59RSF IPRO", pms: null },
    { nome: "DM 59IX61RSF I2X", pms: null },
    { nome: "NEO 510 IPRO", pms: null },
    { nome: "NEO 531 I2X", pms: null },
    { nome: "NEO 560 IPRO", pms: null },
    { nome: "NEO 581E CONKESTA ENLIST", pms: null },
    { nome: "NS-5624 I2X", pms: null },
    { nome: "SOYTECH 541 I2X", pms: null },
    { nome: "TMG-2757 IPRO", pms: null },
    { nome: "TMG-7362 IPRO", pms: null },
    { nome: "22201CE (TMG-GUAPURUVU)", pms: null },
  ],

  milho: [
    { nome: "AG-8701", pms: null },
    { nome: "AG-8707", pms: null },
    { nome: "AG-8780", pms: null },
    { nome: "AG-9021", pms: null },
    { nome: "AS-1666", pms: null },
    { nome: "AS-1757", pms: null },
    { nome: "AS-1850", pms: null },
    { nome: "AS-1868", pms: null },
    { nome: "AS-1877", pms: null },
    { nome: "AS-1901", pms: null },
    { nome: "AS-1955", pms: null },
    { nome: "AS-1985", pms: null },
    { nome: "AS-1991", pms: null },
    { nome: "B2401", pms: null },
    { nome: "B2418", pms: null },
    { nome: "B2507", pms: null },
    { nome: "B2620", pms: null },
    { nome: "B2688", pms: null },
    { nome: "B2702", pms: null },
    { nome: "B2782", pms: null },
    { nome: "B2801", pms: null },
    { nome: "B8211", pms: null },
    { nome: "BM3066", pms: null },
    { nome: "BM3088", pms: null },
    { nome: "BM812", pms: null },
    { nome: "DKB-177", pms: null },
    { nome: "DKB-230", pms: null },
    { nome: "DKB-253", pms: null },
    { nome: "DKB-290", pms: null },
    { nome: "FS395", pms: null },
    { nome: "FS505", pms: null },
    { nome: "FS566", pms: null },
    { nome: "FS575", pms: null },
    { nome: "FS615", pms: null },
    { nome: "FS656", pms: null },
    { nome: "FS670", pms: null },
    { nome: "T-1503", pms: null },
    { nome: "20A55", pms: null },
    { nome: "MG 357", pms: null },
    { nome: "MG 408", pms: null },
    { nome: "MG 535", pms: null },
    { nome: "MG 545", pms: null },
    { nome: "MG 593", pms: null },
    { nome: "MG 616", pms: null },
    { nome: "MG 618", pms: null },
    { nome: "NS-22", pms: null },
    { nome: "NS-44", pms: null },
    { nome: "NS-73", pms: null },
    { nome: "NS-75", pms: null },
    { nome: "NS-80", pms: null },
    { nome: "P25300", pms: null },
    { nome: "P3016", pms: null },
    { nome: "P3282", pms: null },
    { nome: "P3322", pms: null },
    { nome: "P3565", pms: null },
    { nome: "P40537", pms: null },
    { nome: "P4285", pms: null },
    { nome: "SYNK501", pms: null },
    { nome: "SYN8A98 (FEROZ)", pms: null },
    { nome: "SYN7G17 (DEFENDER)", pms: null },
  ],

  feijao: [
    { nome: "ANFC5 (CARIOCA)", pms: null },
    { nome: "ANFC9 (CARIOCA)", pms: null },
    { nome: "ANFC22 (CARIOCA)", pms: null },
    { nome: "ANFC29 (CARIOCA)", pms: null },
    { nome: "BRS ESTEIO (PRETO)", pms: null },
    { nome: "BRS FP403 (PRETO)", pms: null },
    { nome: "BRS FS311 (RAJADO)", pms: null },
    { nome: "IAC NELORE (CARIOCA)", pms: null },
    { nome: "IAC VELOZ (PRETO)", pms: null },
    { nome: "IAC-1849 POLACO (CARIOCA)", pms: null },
    { nome: "IAC-1850 (CARIOCA)", pms: null },
    { nome: "IAC-2051 (CARIOCA)", pms: null },
    { nome: "IAC-2358 UNAMAX (PRETO)", pms: null },
    { nome: "IPR AGUIA (CARIOCA)", pms: null },
    { nome: "IPR QUIRIQUIRI (CARIOCA)", pms: null },
    { nome: "IPR SABIA (CARIOCA)", pms: null },
    { nome: "IPR TAPICURU (PRETO)", pms: null },
    { nome: "IPR TUIUIU (PRETO)", pms: null },
    { nome: "IPR URUTAU (PRETO)", pms: null },
  ],
  trigo: [
    { nome: "ORS BLINDADO", pms: null },
    { nome: "ORS FALCAO", pms: null },
    { nome: "ORS FEROZ", pms: null },
    { nome: "ORS FERRARI", pms: null },
    { nome: "ORS GUARDIAO", pms: null },
    { nome: "ORS SENNA", pms: null },
    { nome: "TBIO ASTRO", pms: null },
    { nome: "TBIO ATON", pms: null },
    { nome: "TBIO AUDAZ", pms: null },
    { nome: "TBIO BIO182385 (TALISMA)", pms: null },
    { nome: "TBIO BIO182455 (TITAN)", pms: null },
    { nome: "TBIO BIO198020 (ENERGIX 8020)", pms: null },
    { nome: "TBIO CALIBRE", pms: null },
    { nome: "TBIO ENERGIX 201", pms: null },
    { nome: "TBIO ENERGIX 202", pms: null },
    { nome: "TBIO ENERGIX 203", pms: null },
    { nome: "TBIO ENERGIX 204", pms: null },
    { nome: "TBIO LENOX (PASTEJO)", pms: null },
    { nome: "TBIO MOTRIZ", pms: null },
    { nome: "TBIO PONTEIRO", pms: null },
    { nome: "TBIO SONIC", pms: null },
    { nome: "TBIO TORUK", pms: null },
    { nome: "TBIO TRUNFO", pms: null },
    { nome: "TBIO WBC201347 (VELOZ)", pms: null },
    { nome: "TBIO WBC221301 (DINAMO)", pms: null },
  ],

  // Formulações/produtos de adubo cotados pelo cliente — pms não se aplica
  // aqui (fica sempre null), é só pra reaproveitar o mesmo mecanismo de
  // busca/sugestão do campo. O NPK é lido do próprio nome quando presente
  // (ver lerFormulacao() em app.js); itens sem número no nome (ex.: "Ureia
  // Granulada", produtos foliares) continuam pesquisáveis mas não preenchem
  // N/P/K sozinhos — o usuário completa manualmente.
  adubacao: [
    { nome: "02.23.23 CIBRA/BRFERTIL", pms: null },
    { nome: "02.23.23 MISTURA DE GRANULOS", pms: null },
    { nome: "02.23.23 STRATUN MOSAIC", pms: null },
    { nome: "02.23.23 EVOLUTION TOPMIX YARA", pms: null },
    { nome: "04.23.20 +0,18B PLUS BAG COASUL/MOSAIC", pms: null },
    { nome: "04.30.10 MISTURA DE GRANULOS", pms: null },
    { nome: "HAKAPHOS AZUL 20.05.05 COMPO", pms: null },
    { nome: "11.52.00 MAP", pms: null },
    { nome: "12.31.17 EVOLUTION TOPMIX YARA", pms: null },
    { nome: "12.32.18 MISTURA DE GRANULOS", pms: null },
    { nome: "13.24.12 YARAMILA", pms: null },
    { nome: "YARAMILA PRATICALE 22.10.10 2%S 0,1%ZN", pms: null },
    { nome: "08.20.15 MG BRFERTIL/COONAGRO/FERTIPAR", pms: null },
    { nome: "08.20.15 YARA/MOSAIC MISTURA DE GRANULOS", pms: null },
    { nome: "09.15.15 YARABASA POWERSTART", pms: null },
    { nome: "10.15.15 MG CIBRA/BRFERTIL/CONAGRO/FERTIPAR", pms: null },
    { nome: "10.15.15 MISTURA DE GRANULOS", pms: null },
    { nome: "10.20.18 +0,16B PERFORMA PLUS MOSAIC", pms: null },
    { nome: "03.21.21 NPK 7CA 5S+MICROS YARABASA", pms: null },
    { nome: "ASPIRE 00.00.58+0,5B (KCL+B) MOSAIC", pms: null },
    { nome: "BAKPRO", pms: null },
    { nome: "BASFOLIAR BLACK EVOLUTION COMPO", pms: null },
    { nome: "BASFOLIAR CITOBOR COMPO", pms: null },
    { nome: "BASFOLIAR COMOL HC (Mo12% Co0,2%) COMPO", pms: null },
    { nome: "BASFOLIAR COMOL TOP (Mo12% Co0,2%) COMPO", pms: null },
    { nome: "BIOATIVADOR FOLHA (Mn0,85% Zn0,85% Mg1% N2,5% S21% COT4,7%)", pms: null },
    { nome: "BIOATIVADOR RAIZ (N4,7% Zn0,75% COT4,7%) NORTOX", pms: null },
    { nome: "CLORETO DE POTASSIO", pms: null },
    { nome: "33.00.00 UREIA PROTEGIDA", pms: null },
    { nome: "UREIA PROTEGIDA 45.00.00", pms: null },
    { nome: "UREIA GRANULADA", pms: null },
    { nome: "COOPER N 33.00.00 FECOAGRO", pms: null },
    { nome: "COOPER N 40.00.00 FECOAGRO", pms: null },
    { nome: "SULFATO DE AMONIA GRANULADO", pms: null },
    { nome: "YARA BELA 27.00.00", pms: null },
    { nome: "SUPERFOSFATO SIMPLES", pms: null },
  ],
};
