// Catálogo de cultivares — Coasul
// PMS/PMG ainda não preenchido (null) — completar depois com dados oficiais
// Extraído de: histórico de vendas de milho (imagem) e SEMENTE_DE_SOJA_VENDIDAS.pdf
//
// Usado pela busca/sugestão do campo "Cultivar cotada" (ver o bloco de busca
// de cultivar em app.js). Cada item: { nome, pms }. pms em gramas por 1.000
// sementes — null enquanto não temos o valor oficial; o indicador de PMS/PMG
// automático só aparece pra itens com esse dado preenchido.
const CULTIVARES = {
  soja: [
    { nome: "51IX51RSF (TROVAO) I2X", pms: null },
    { nome: "53IX55RSF (IMUNE) TF I2X", pms: null },
    { nome: "55I57RSF IPRO (ZEUS)", pms: null },
    { nome: "55IX56RSF I2X (ORION)", pms: null },
    { nome: "56IX58RSF I2X (TITANIUM)", pms: null },
    { nome: "57I59RSF IPRO (CROMO)", pms: null },
    { nome: "57K56RSF TF CE (GRAFENO)", pms: null },
    { nome: "AS-3577 XTEND", pms: null },
    { nome: "AS-3595 (5995 I2X)", pms: null },
    { nome: "DM 54IX57RSF I2X", pms: null },
    { nome: "DM 56I59RSF IPRO", pms: null },
    { nome: "DM 59IX61RSF I2X", pms: null },
    { nome: "NEO 510 IPRO", pms: null },
    { nome: "NEO 531 I2X", pms: null },
    { nome: "NEO 560 IPRO", pms: null },
    { nome: "NEO 581E CONKESTA ENLIST", pms: null },
    { nome: "NS-5624 I2X", pms: null },
    { nome: "SOYTECH 541 I2X", pms: null },
    { nome: "TMG-2757 IPRO", pms: null },
    { nome: "TMG-7362 IPRO", pms: null },
    { nome: "22201CE (TMG-GUAPURUVU)", pms: null },
  ],

  milho: [
    { nome: "AG-8701", pms: null },
    { nome: "AG-8707", pms: null },
    { nome: "AG-8780", pms: null },
    { nome: "AG-9021", pms: null },
    { nome: "AS-1666", pms: null },
    { nome: "AS-1757", pms: null },
    { nome: "AS-1850", pms: null },
    { nome: "AS-1868", pms: null },
    { nome: "AS-1877", pms: null },
    { nome: "AS-1901", pms: null },
    { nome: "AS-1955", pms: null },
    { nome: "AS-1985", pms: null },
    { nome: "AS-1991", pms: null },
    { nome: "B2401", pms: null },
    { nome: "B2418", pms: null },
    { nome: "B2507", pms: null },
    { nome: "B2620", pms: null },
    { nome: "B2688", pms: null },
    { nome: "B2702", pms: null },
    { nome: "B2782", pms: null },
    { nome: "B2801", pms: null },
    { nome: "B8211", pms: null },
    { nome: "BM3066", pms: null },
    { nome: "BM3088", pms: null },
    { nome: "BM812", pms: null },
    { nome: "DKB-177", pms: null },
    { nome: "DKB-230", pms: null },
    { nome: "DKB-253", pms: null },
    { nome: "DKB-290", pms: null },
    { nome: "FS395", pms: null },
    { nome: "FS505", pms: null },
    { nome: "FS566", pms: null },
    { nome: "FS575", pms: null },
    { nome: "FS615", pms: null },
    { nome: "FS656", pms: null },
    { nome: "FS670", pms: null },
    { nome: "T-1503", pms: null },
    { nome: "20A55", pms: null },
    { nome: "MG 357", pms: null },
    { nome: "MG 408", pms: null },
    { nome: "MG 535", pms: null },
    { nome: "MG 545", pms: null },
    { nome: "MG 593", pms: null },
    { nome: "MG 616", pms: null },
    { nome: "MG 618", pms: null },
    { nome: "NS-22", pms: null },
    { nome: "NS-44", pms: null },
    { nome: "NS-73", pms: null },
    { nome: "NS-75", pms: null },
    { nome: "NS-80", pms: null },
    { nome: "P25300", pms: null },
    { nome: "P3016", pms: null },
    { nome: "P3282", pms: null },
    { nome: "P3322", pms: null },
    { nome: "P3565", pms: null },
    { nome: "P40537", pms: null },
    { nome: "P4285", pms: null },
    { nome: "SYNK501", pms: null },
    { nome: "SYN8A98 (FEROZ)", pms: null },
    { nome: "SYN7G17 (DEFENDER)", pms: null },
  ],

  feijao: [],
  trigo: [],
};
